---
- name: Create Palo Alto Networks Security Rule
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Authenticate to the API and get access token
      ansible.builtin.import_tasks: tasks/authenticate.yml

    - name: Create the 'Ansible Rule' security rule
      block:
        - name: Attempt to create the security rule via API
          ansible.builtin.uri:
            url: "{{ api_base_url }}/config/security/v1/security-rules"
            method: POST
            headers:
              Content-Type: "application/json"
              Authorization: "Bearer {{ api_access_token }}" # This comes from authenticate.yml
            body_format: json
            body:
              name: "Ansible Rule"
              description: "Rule created via Ansible"
              folder: "Shared"
              disabled: false
              from: ["any"]
              to: ["any"]
              source: ["any"]
              destination: ["any"]
              source_user: ["any"]
              category: ["any"]
              application: ["any"]
              service: ["any"]
              source_hip: ["any"]
              destination_hip: ["any"]
              action: "allow"
              negate_source: false
              negate_destination: false
              profile_setting:
                group:
                  - "best-practice"
            status_code: 201
            validate_certs: true # Set to false if using self-signed certs
          register: security_rule_response

        - name: Display success message
          ansible.builtin.debug:
            msg: "Successfully created security rule 'Ansible Rule'."

      rescue:
        - name: Fail playbook with a clear error message from the API
          ansible.builtin.fail:
            msg: |
              Failed to create the security rule. The API returned the following error:
              {{ security_rule_response.json | to_json }}
